aliases:
  - &defaults
    working_directory: ~/abracad
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: "true"

version: 2
jobs:
  unit_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test-all

workflows:
  version: 2
  abracad:
    jobs:
      - unit_test